### ISSUE TITLE
Server crashes on empty username for login

### ISSUE THREAD

**Issue by stevejarvis** [or-drop-tables-team/sup#26]
If the client sends a blank username for login the server crashes with a buffer out of bounds error. The server should check for a blank entry and guard against this case. See #25 for more info and steps to reproduce (#25 is the client side issue for this bug). 

Here's the trace from a crash:

```
sjarvis@verona ~/workspace/sup $ java -jar client/target/client-0.0.1.jar 
Received a new connection
Logging in with 
read "login " from Thread-0
Exception in thread "Thread-0" java.lang.ArrayIndexOutOfBoundsException: 1
    at org.server.SupServer$SupClientHandler.run(SupServer.java:78)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by stevejarvis** [comment]
The server now checks for it, but also the client will not send it.
